# Generated by Django 2.0b1 on 2017-12-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20171205_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(max_length=100),
        ),
    ]
